### ISSUE TITLE
Errors in Docs

### ISSUE THREAD

**Issue by madebymccoy** [MadScrewdriver/qsketchmetric#16]
Hi,

Just started using the Library - absolutely brilliant tool!

I had a really steep learning curve, mostly I found from a number of missing details, and a few errors/typos in the docs. One of the bigger ones is the interchanged use of "Build" and "Buld" for the MTEXT. Seems not an issue for renderer.py, but is referenced in semiautomatic.py.

I've also struggled to understand the ideal graph of constraints to build for an object, so an explanation of that and different examples would be incredibly useful!

I'm happy to edit and push my updates, or can list issues I've found?

Thanks

**Comment by MadScrewdriver** [comment]
Thanks so much for your positive feedback on the library!
It's really encouraging to hear that you find it useful.

I'm planning to put together some YouTube tutorials soon
to help ease the learning process, especially focusing on
parametric modelling and the use of constraints.

Your idea to include more examples is a great one, and I'll definitely be adding those in!

If you're interested in contributing, that would be fantastic!
Feel free to fork the repository and send over pull requests.
As I'm managing this project in my spare time,
it's great to have others involved and interested!

Again, thanks for your support and feedback!

**Comment by MadScrewdriver** [comment]
For anyone still facing a steep learning curve, feel free to reach out!

I've added some [examples](https://github.com/MadScrewdriver/qsketchmetric/tree/main/examples) of parameterized files and started a [YouYube tutorial](https://www.youtube.com/playlist?list=PLpVxwQmtfqH4TpyFuB5yyvXj0Zwru7Nl8) on QSketchMetric.  Please feel free to add your own examples of parameterized DXF files to the repository.
